In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_d=pd.read_csv('drive/MyDrive/Stock_Market_Sharingan/jpm_us_d.csv')
df_w=pd.read_csv('drive/MyDrive/Stock_Market_Sharingan/jpm_us_w.csv')
df_m=pd.read_csv('drive/MyDrive/Stock_Market_Sharingan/jpm_us_m.csv')
df_q=pd.read_csv('drive/MyDrive/Stock_Market_Sharingan/jpm_us_q.csv')
df_y=pd.read_csv('drive/MyDrive/Stock_Market_Sharingan/jpm_us_y.csv')

df_d.head()

     Date_d    Open_d    High_d     Low_d   Close_d     Volume_d
0  1/2/1970  3.750242  3.750242  3.710047  3.750242  24543.66216
1  1/5/1970  3.750242  3.759785  3.720117  3.750242  32040.91286
2  1/6/1970  3.750242  3.789882  3.730075  3.789882  27954.70574
3  1/7/1970  3.800118  3.899718  3.800118  3.879814  73633.92196
4  1/8/1970  3.869884  3.869884  3.820285  3.869884  21817.32246

In [ ]:
df_d['Datetime_d'] = pd.to_datetime(df_d['Date_d'])
df_m['Datetime_m'] = pd.to_datetime(df_m['Date_m'])
df_y['Datetime_y'] = pd.to_datetime(df_y['Date_y'])

In [ ]:
# Extract year
df_d['year'] = df_d['Datetime_d'].dt.year
df_m['year'] = df_m['Datetime_m'].dt.year
df_y['year'] = df_y['Datetime_y'].dt.year

# Extract month
df_d['month'] = df_d['Datetime_d'].dt.month
df_m['month'] = df_m['Datetime_m'].dt.month
df_y['month'] = df_y['Datetime_y'].dt.month

# Perform the join
merged_df = pd.merge(df_d, df_m, on=['year', 'month'], how='inner')
merged_df = pd.merge(merged_df, df_y, on='year', how='inner')
merged_df.head()

,Date_d,Open_d,High_d,Low_d,Close_d,Volume_d,Datetime_d,year,month_x,Date_m,...,Volume_m,Datetime_m,Date_y,Open_y,High_y,Low_y,Close_y,Volume_y,Datetime_y,month_y
0,1/2/1970,3.750242,3.750242,3.710047,3.750242,24543.66216,1970-01-02,1970,1,1/31/1970,...,783392.2469,1970-01-31,12/31/1970,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31,12
1,1/5/1970,3.750242,3.759785,3.720117,3.750242,32040.91286,1970-01-05,1970,1,1/31/1970,...,783392.2469,1970-01-31,12/31/1970,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31,12
2,1/6/1970,3.750242,3.789882,3.730075,3.789882,27954.70574,1970-01-06,1970,1,1/31/1970,...,783392.2469,1970-01-31,12/31/1970,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31,12
3,1/7/1970,3.800118,3.899718,3.800118,3.879814,73633.92196,1970-01-07,1970,1,1/31/1970,...,783392.2469,1970-01-31,12/31/1970,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31,12
4,1/8/1970,3.869884,3.869884,3.820285,3.869884,21817.32246,1970-01-08,1970,1,1/31/1970,...,783392.2469,1970-01-31,12/31/1970,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31,12

In [ ]:
# Get column names as a list
column_list = merged_df.columns.tolist()

# Print the list of columns
print(column_list)

['Date_d', 'Open_d', 'High_d', 'Low_d', 'Close_d', 'Volume_d', 'Datetime_d', 'year', 'month_x', 'Date_m', 'Open_m', 'High_m', 'Low_m', 'Close_m', 'Volume_m', 'Datetime_m', 'Date_y', 'Open_y', 'High_y', 'Low_y', 'Close_y', 'Volume_y', 'Datetime_y', 'month_y']

In [ ]:
merged_df.drop(columns=['year', 'month_x', 'month_y', 'Date_d', 'Date_m', 'Date_y'], inplace=True)
merged_df.head()

,Open_d,High_d,Low_d,Close_d,Volume_d,Datetime_d,Open_m,High_m,Low_m,Close_m,Volume_m,Datetime_m,Open_y,High_y,Low_y,Close_y,Volume_y,Datetime_y
0,3.750242,3.750242,3.710047,3.750242,24543.66216,1970-01-02,3.750242,3.910217,3.520086,3.580184,783392.2469,1970-01-31,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31
1,3.750242,3.759785,3.720117,3.750242,32040.91286,1970-01-05,3.750242,3.910217,3.520086,3.580184,783392.2469,1970-01-31,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31
2,3.750242,3.789882,3.730075,3.789882,27954.70574,1970-01-06,3.750242,3.910217,3.520086,3.580184,783392.2469,1970-01-31,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31
3,3.800118,3.899718,3.800118,3.879814,73633.92196,1970-01-07,3.750242,3.910217,3.520086,3.580184,783392.2469,1970-01-31,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31
4,3.869884,3.869884,3.820285,3.869884,21817.32246,1970-01-08,3.750242,3.910217,3.520086,3.580184,783392.2469,1970-01-31,3.750242,4.240112,2.859895,4.090345,12873211.71,1970-12-31

In [ ]:
# Get column names as a list
column_list = merged_df.columns.tolist()

# Print the list of columns
print(len(column_list))

18